## ***Numerical Python***

In [ ]:
import numpy as np

In [ ]:
list1 = [1,2,3,4,5,6,7,8,9,10] # list

In [ ]:
arr = np.array(list1) # list convert in Array

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
d = np.array([[1,2,3],[4,5,6]])

In [ ]:
d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a = np.matrix(d)
type(a)

numpy.matrix

In [ ]:
d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a = np.array(list1)

In [ ]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
c = a # solo copy

In [ ]:
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
c[0] = 100

In [ ]:
c

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [ ]:
a

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [ ]:
b = np.copy(a) # deep copy

In [ ]:
b

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [ ]:
a

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [ ]:
b[0] = 125

In [ ]:
b

array([125,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [ ]:
a

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [ ]:
l1 = np.fromfunction(lambda i,j : i==j,(3,3))

In [ ]:
ar = np.array(l1)

In [ ]:
ar

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [ ]:
ar2 = np.array([[1,2,3,4],[5,6,7,8]])

In [ ]:
ar.size

9

In [ ]:
ar2.size

8

In [ ]:
ar.shape

(3, 3)

In [ ]:
ar2.shape

(2, 4)

In [ ]:
list(range(5))

[0, 1, 2, 3, 4]

In [ ]:
np.arange(0.5,5.0,0.2)

array([0.5, 0.7, 0.9, 1.1, 1.3, 1.5, 1.7, 1.9, 2.1, 2.3, 2.5, 2.7, 2.9,
       3.1, 3.3, 3.5, 3.7, 3.9, 4.1, 4.3, 4.5, 4.7, 4.9])

In [ ]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
ar4 = np.zeros((3,4,5)) # 3 Array || 4 Rows || 5 Columns

In [ ]:
ar4.ndim

3

In [ ]:
np.ones(4)

array([1., 1., 1., 1.])

In [ ]:
N =np.ones((2,3,4))

In [ ]:
N

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
N+5

array([[[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]],

       [[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]]])

In [ ]:
N*2

array([[[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]],

       [[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]]])

In [ ]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.eye(4) # squere matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.linspace(2,3,4)

array([2.        , 2.33333333, 2.66666667, 3.        ])

In [ ]:
np.logspace(2,3)

array([ 100.        ,  104.81131342,  109.8541142 ,  115.13953993,
        120.67926406,  126.48552169,  132.57113656,  138.94954944,
        145.63484775,  152.64179672,  159.98587196,  167.68329368,
        175.75106249,  184.20699693,  193.06977289,  202.35896477,
        212.09508879,  222.29964825,  232.99518105,  244.20530945,
        255.95479227,  268.26957953,  281.1768698 ,  294.70517026,
        308.88435965,  323.74575428,  339.32217719,  355.64803062,
        372.75937203,  390.69399371,  409.49150624,  429.19342601,
        449.8432669 ,  471.48663635,  494.17133613,  517.94746792,
        542.86754393,  568.9866029 ,  596.36233166,  625.05519253,
        655.12855686,  686.648845  ,  719.685673  ,  754.31200634,
        790.60432109,  828.64277285,  868.51137375,  910.29817799,
        954.09547635, 1000.        ])

# ***Array Manipulation***

In [ ]:
import numpy as np

In [ ]:
arr = np.random.randint(1,10,(3,4))

In [ ]:
arr

array([[5, 3, 9, 1],
       [5, 6, 2, 8],
       [1, 9, 1, 2]])

In [ ]:
arr.reshape(6,2)

array([[5, 3],
       [9, 1],
       [5, 6],
       [2, 8],
       [1, 9],
       [1, 2]])

In [ ]:
arr.T

array([[5, 5, 1],
       [3, 6, 9],
       [9, 2, 1],
       [1, 8, 2]])

In [ ]:
arr3 = arr.flatten()

In [ ]:
arr3.ndim

1

In [ ]:
np.expand_dims(arr3,axis=1)

array([[5],
       [3],
       [9],
       [1],
       [5],
       [6],
       [2],
       [8],
       [1],
       [9],
       [1],
       [2]])

In [ ]:
np.squeeze(arr3)

array([5, 3, 9, 1, 5, 6, 2, 8, 1, 9, 1, 2])

In [ ]:
np.repeat(arr3,3)

array([5, 5, 5, 3, 3, 3, 9, 9, 9, 1, 1, 1, 5, 5, 5, 6, 6, 6, 2, 2, 2, 8,
       8, 8, 1, 1, 1, 9, 9, 9, 1, 1, 1, 2, 2, 2])

In [ ]:
np.roll(arr3,2)

array([1, 2, 5, 3, 9, 1, 5, 6, 2, 8, 1, 9])

In [ ]:
np.diag(arr3)

array([[5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2]])

## ***Numpy - Binary Oprations***

In [ ]:
arr4 = np.random.randint(1,10,(2,2))

In [ ]:
arr4

array([[1, 6],
       [3, 1]])

In [ ]:
arr5 = np.random.randint(1,10,(2,2))

In [ ]:
arr5

array([[9, 2],
       [1, 5]])

In [ ]:
arr4 + arr5

array([[10,  8],
       [ 4,  6]])

In [ ]:
arr4 * arr5 # +,-,*,/,&,**,|,>,<,

array([[ 9, 12],
       [ 3,  5]])

## ***Numpy - String Opration***

In [ ]:
arr6 = np.array(["ram","sham"])

In [ ]:
arr6

array(['ram', 'sham'], dtype='<U4')

In [ ]:
np.char.upper(arr6)

array(['RAM', 'SHAM'], dtype='<U4')

In [ ]:
np.char.title(arr6)

array(['Ram', 'Sham'], dtype='<U4')

In [ ]:
np.char.capitalize(arr6)

array(['Ram', 'Sham'], dtype='<U4')

### ***Matematical Oprations***

In [ ]:
arr6

array(['ram', 'sham'], dtype='<U4')

In [ ]:
arr5

array([[9, 2],
       [1, 5]])

In [ ]:
np.sin(arr5) # cos,Log10, exponent,min,max,var,median,power,etc....

array([[ 0.41211849,  0.90929743],
       [ 0.84147098, -0.95892427]])